# Generated by Django 3.2.9 on 2021-11-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
