# Generated by Django 3.2.9 on 2021-11-23 13:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('online_forum', '0002_auto_20211123_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=100, size=[50, 80], upload_to='authors'),
        ),
    ]
