# Generated by Django 3.2.9 on 2021-11-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_forum', '0005_auto_20211124_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default='zero', max_length=40),
        ),
    ]
